// Code generated by go-swagger; DO NOT EDIT.

package budgets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new budgets API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for budgets API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetBudgets(params *GetBudgetsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetBudgetsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetBudgets lists budgets

Returns budgets list with summary information
*/
func (a *Client) GetBudgets(params *GetBudgetsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetBudgetsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetBudgetsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getBudgets",
		Method:             "GET",
		PathPattern:        "/budgets",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetBudgetsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetBudgetsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetBudgetsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
