// Code generated by go-swagger; DO NOT EDIT.

package budgets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetBudgetsParams creates a new GetBudgetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBudgetsParams() *GetBudgetsParams {
	return &GetBudgetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBudgetsParamsWithTimeout creates a new GetBudgetsParams object
// with the ability to set a timeout on a request.
func NewGetBudgetsParamsWithTimeout(timeout time.Duration) *GetBudgetsParams {
	return &GetBudgetsParams{
		timeout: timeout,
	}
}

// NewGetBudgetsParamsWithContext creates a new GetBudgetsParams object
// with the ability to set a context for a request.
func NewGetBudgetsParamsWithContext(ctx context.Context) *GetBudgetsParams {
	return &GetBudgetsParams{
		Context: ctx,
	}
}

// NewGetBudgetsParamsWithHTTPClient creates a new GetBudgetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBudgetsParamsWithHTTPClient(client *http.Client) *GetBudgetsParams {
	return &GetBudgetsParams{
		HTTPClient: client,
	}
}

/*
GetBudgetsParams contains all the parameters to send to the API endpoint

	for the get budgets operation.

	Typically these are written to a http.Request.
*/
type GetBudgetsParams struct {

	/* IncludeAccounts.

	   Whether to include the list of budget accounts
	*/
	IncludeAccounts *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get budgets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBudgetsParams) WithDefaults() *GetBudgetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get budgets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBudgetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get budgets params
func (o *GetBudgetsParams) WithTimeout(timeout time.Duration) *GetBudgetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get budgets params
func (o *GetBudgetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get budgets params
func (o *GetBudgetsParams) WithContext(ctx context.Context) *GetBudgetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get budgets params
func (o *GetBudgetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get budgets params
func (o *GetBudgetsParams) WithHTTPClient(client *http.Client) *GetBudgetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get budgets params
func (o *GetBudgetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIncludeAccounts adds the includeAccounts to the get budgets params
func (o *GetBudgetsParams) WithIncludeAccounts(includeAccounts *bool) *GetBudgetsParams {
	o.SetIncludeAccounts(includeAccounts)
	return o
}

// SetIncludeAccounts adds the includeAccounts to the get budgets params
func (o *GetBudgetsParams) SetIncludeAccounts(includeAccounts *bool) {
	o.IncludeAccounts = includeAccounts
}

// WriteToRequest writes these params to a swagger request
func (o *GetBudgetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IncludeAccounts != nil {

		// query param include_accounts
		var qrIncludeAccounts bool

		if o.IncludeAccounts != nil {
			qrIncludeAccounts = *o.IncludeAccounts
		}
		qIncludeAccounts := swag.FormatBool(qrIncludeAccounts)
		if qIncludeAccounts != "" {

			if err := r.SetQueryParam("include_accounts", qIncludeAccounts); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
