// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// LoanAccountPeriodicValue loan account periodic value
//
// swagger:model LoanAccountPeriodicValue
type LoanAccountPeriodicValue map[string]int64

// Validate validates this loan account periodic value
func (m LoanAccountPeriodicValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this loan account periodic value based on context it is used
func (m LoanAccountPeriodicValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
